name: player
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  freezed: ^2.1.0+1
  just_audio: ^0.9.28
  just_audio_background: ^0.0.1-beta.7
  audio_service: ^0.18.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/



